name: Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username (e.g., "atmghan")
          password: ${{ secrets.DOCKER_PASSWORD }}   # Docker Hub access token

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .  # Build context (current directory)
          file: ./Dockerfile  # Explicit path to Dockerfile
          push: true
          tags: atmghan/ecommerce-web:latest