name: Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # e.g., "atmghan"
          password: ${{ secrets.DOCKER_PASSWORD }}   # Docker Hub token

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./ecommerce-api  # Path to the directory containing Dockerfile
          file: ./ecommerce-api/Dockerfile  # Explicit path to Dockerfile
          push: true
          tags: atmghan/ecommerce-web:latest